baseURL = "https://odin-lang.org"
title = "Odin Programming Language"
theme = "odin"

[params]
slogan = "The Data-Oriented Language for Sane Software Development."

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
endLevel = 4

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "docs"
name = "Docs"
url = "/docs"
weight = 2

[[menu.main]]
identifier = "packages"
name = "Packages"
url = "https://pkg.odin-lang.org/"
weight = 3

[[menu.main]]
identifier = "news"
name = "News"
url = "/news"
weight = 4

[[menu.main]]
identifier = "showcase"
name = "Showcase"
url = "/showcase"
weight = 5

[[menu.main]]
identifier = "community"
name = "Community"
url = "/community"
weight = 6

[[menu.main]]
identifier = "github"
name = "GitHub"
url = "https://github.com/odin-lang/Odin"
weight = 7
